import type { Metadata } from "next";
import "./globals.css";
import { openSans, yesevaOne, signika, garamond } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${openSans.variable} ${yesevaOne.variable} ${signika.variable} ${garamond.variable}`}
    >
      <body className="font-sans">{children}</body>
    </html>
  );
}
